rootProject.name = "CustomEnchantLoader"
include("loader")
include("behead")
include("chain-collection")
include("smelt")
include("farm")
include("farmer")
include("damage-protection")
include("gold-digger")
include("eternal")
